### ISSUE TITLE
Detailed Documentation

### ISSUE THREAD

**Issue by mhechthz** [weymouth/lily-pad#16]
Hi,

this is more a request than an issue. I wonder if there is an accompanying description on the core of the system. It ist quite fast and forces me to use it for other applications. But to adapt this (especially for 3D) a much more detailed documentation would be necessary. Currently it is impossible or at least hard for me to change the code for my own needs. Or do you think your thesis is sufficient? I downloaded it but didn't start to read.

Nevertheless: Good Work!

**Comment by weymouth** [comment]
Hey Michael,

The papers referenced in the documentation are a complete write-up of the methodology. 

However, if you are thinking about extending to 3D, then I suggest looking at https://github.com/weymouth/WaterLily, which is designed for 3D use and is written in Julia. Note that 3D is much more of a challenge for geometries and visualization than it is for the fluid dynamics.

**Comment by mhechthz** [comment]
Cool, thank you. I will check this.
