### ISSUE TITLE
Question : Javascript library

### ISSUE THREAD

**Issue by ThreePointSquare** [weymouth/lily-pad#18]
Has there been any work towards converting the code from processing to javascript.

**Comment by weymouth** [comment]
Nope. But it is being ported over to Julia https://github.com/weymouth/WaterLily.jl

**Comment by ThreePointSquare** [comment]
Cool. thanks for the info!. I did start porting to JS and ran into some snags so i thought id ask before i went any further. not for the faint of heart.

**Comment by weymouth** [comment]
Yeah - it's not as bad as most CFD codes, but it's not a walk-in-the-park
either. I have put a few fluids things in JS.
https://weymouth.github.io/fluid-dynamics/

Gabriel D Weymouth
_______________________________________________
"Computers are useless. They can only give you answers." Pablo Picasso
