### ISSUE TITLE
Importing Custom Shapes from CAD 

### ISSUE THREAD

**Issue by ThreePointSquare** [weymouth/lily-pad#19]
Is there a way to import custom shapes from a CAD platform? I was wanting to utilize grasshopper in rhino to run some optimizations on forms for architecture. I can most definitely read and stream data from the program looking at the audry test example. I was hoping to run a loop over a form or set of forms to focus wind flow. Old research, ongoing pet project now.

**Comment by ThreePointSquare** [comment]
https://www.researchgate.net/publication/349088301_PRINCIPLES_AND_DESIGN_GUIDELINES_FOR_BUILDING_INTEGRATED_WIND_POWER_RECOMMENDATIONS_LEADING_TOWARDS_A_SELF-POWERED_BUILT_ENVIRONMENT

**Comment by weymouth** [comment]
The underlying data structure defining geometries is just an array of
points - so anything that you can translate into that format will work.

Gabriel D Weymouth
_______________________________________________
"Computers are useless. They can only give you answers." Pablo Picasso

**Comment by ThreePointSquare** [comment]
That's great to hear. Actually that makes a ton of sense now. And preferably fits well with gridding in the pipeline. Im traveling now but will have more questions in the coming weeks!thanks for being responsive truly appreciate it.

**Comment by LongWeiZJU** [comment]
It seems that we need to specify `ma` in definition of an arbitrary shape body class. 
Then how to set `ma` for a polygon?
