### ISSUE TITLE
Meaning of NACA Variable "ma"

### ISSUE THREAD

**Issue by jwethan** [weymouth/lily-pad#20]
I'm working on a new adaptation of the code to simulate heaving and passive pitching foils. I'm trying to implement code to treat the pitching about the leading edge as a torsional spring in response to the moment imposed by the fluid. I am using the NACA geometry as the body and I was wondering what the variable "ma" is holding in the NACA file. It's used in the Body "react" function in computing the dynamics, what does it represent? Seems like it has something to due with the shape inertias but I'm not sure.

All help is appreciated, thanks.

**Comment by weymouth** [comment]
It is the body's **added** mass.

**Comment by jwethan** [comment]
I may be confused, but why does it have 3 different components? The z-component of the PVector is used to calculate the new ddotphi in the rotational dynamics, what is that accounting for?

ddotphi = M + ma.z*ddotphi/(I0 + ma.z);

I don't see the need for it in my equations, so I'm wondering if I am missing something.

Why are both the moment of inertia calculated from Body getArea() and ma.z needed?

Thanks for the help.

**Comment by weymouth** [comment]
Apologies. It is the added mass. The linear inertia due to accelerating the surrounding water from translation in x or y or rotation around z.
