### ISSUE TITLE
Fluid "twitching" when simulating non-convex airfoils

### ISSUE THREAD

**Issue by jwethan** [weymouth/lily-pad#21]
I'm working on testing new airfoil shapes in the program and I've noticed irregularities in the fluid when the shape has non-convex sections. Sort of like a weird twitching at the tip that I've noticed only forms when the shape has a concave section. 

Does Lily Pad have the capability to simulate non-convex shapes accurately? If not why is the solver limited in that aspect and is there any way to accommodate concave shapes?

Any insight is appreciated.

**Comment by weymouth** [comment]
Lily-Pad isn't under development any longer. If you are interested in a more advanced and faster version of the software, check out [WaterLily](https://github.com/weymouth/WaterLily.jl)
