### ISSUE TITLE
Multiple Foil Tests

### ISSUE THREAD

**Issue by dankoenig** [weymouth/lily-pad#8]
Is it possible to have a BodyUnion of two FoilTests? i.e. have two of the FoilTest classes within one flow in order to determine the pressure and force for each, and their interaction with each other?

body = BodyUnion(new FoilTest(x,y,...), FoilTest(x2,y2....));

does not work

**Comment by weymouth** [comment]
That doesn't make sense. BodyUnion takes the union of two **bodies**, not two test cases. If you want to look at two foils you need to use:

`pair = BodyUnion(new NACA(arguments), new NACA(other arguments));`

**Comment by dankoenig** [comment]
I see. I think the problem im facing is trying to get the outputs from
FoilTest (pressure, force), as well as having the ability to supply a
pitchAmp to each foil. Any suggestions?

Thank you!

**Comment by weymouth** [comment]
I'm thinking about updating body Union and the update routines to make this easier since it seems user unfriendly. Can you help me test it out?

**Comment by dankoenig** [comment]
Absolutely, I will be able to today between 530 and 730 EST.

thank you.

**Comment by weymouth** [comment]
The new version of BodyUnion lets you add as many bodies on as you want. To change their dynamics you could use 

`for (Body body : group.bodyList){body.follow(kinematics);}`

where `kinematics` is a function that returns a PVector with (x,y,phi) as in the new foil example in the LilyPad.pde file.

As for forces, look at the `SaveArray` class in the same (BodyUnion.pde) file. You can use `saved.printPressForce(pressure, group, L)` to write the pressure force on all the bodies to the same file.
