### ISSUE TITLE
two phase code always crashes for me.

### ISSUE THREAD

**Issue by damian-666** [weymouth/lily-pad#9]
first i just uncomment the code so tat the two phase file does all the work.  this usually gives a result.
i needed to use the prior pix, to use the settings to set the size, in the middle of teh file like on the my last suggestested change

64 
322 array out of bounds.

  Field( Field b, int is, int n, int js, int m ){
    this.n = n;
    this.m = m;
    a = new float[n][m];
    btype = b.btype;
    bval = b.bval;
    for( int i=0; i<n; i++){
    for( int j=0; j<m; j++){
      a[i][j] = b.a[i+is][j+js];
    }}

I would love it if a wave can eat a gulp air and it bubbles up..., or is sprayed out as the wave crashes.. while salf walter and refresh water or volcanic dust settles in ...i see this in REEF3d. vids on their site. wich is similar in setup..   the  mesh based code in galerkin has got to be 10x better for the computational cost, but if its too hard to work with .. whats the use..

**Comment by weymouth** [comment]
Thanks for reporting this bug. It was a holdout from when the code was updated to run on Processing 3. I also found and removed some redundant code. [I pushed up the new code](https://github.com/weymouth/lily-pad/commit/2d954cd8701187de896622ee2ddd4c9ed7be4a49), so you just need to pull to get the new version. The test simulation for TwoPhase is the classic dam-break; lots of air-gulping.

**Comment by damian-666** [comment]
re:   2d side view waves, Adaptive multigrid, air gulping breaking waves ,
temperature field, breaking wave generator and  test code...

Thank you  Dr. Weymouth,


"dam-break; lots of air-gulping"      powerful crashing waves..   that is
what i want to try and test...   are there any pde files for this test?
 Or should I go to the other related vaults.
what  i am most interested is in a 2d side view of a large wave crashing,
with a surfer inside ( that I have already made)  or various fish and
creatures in 2d, underwater,  and above.     Air   , lava ,water, fresh,
and salt.    sulfuric gasses..  more that 2 phases would be welcome , but 2
is enough.   Zooming out to see a big ocean would be ideal, but i can make
the wave crashing zone a separate simulation, and pass the state between
using an overlap region.

.. With crude methods I have scaled a wave to 100 ft and was able to turn
off the engines and surf it in a thin paneled boat, even though the wave is
not breaking.  But I am in the process of reworking all my fluid and wind
field code, tossing much away.  I use a simple panel and drag model for
immersed boundaries.  There are two calculation  point,  on each panel when
unconnected or big enough , so that they float like leaves in air.   I made
a powered flap propelled  sperm model in an hour to two, using 1/ panel
length squared flux drag estimation code.     But my crude model lacks
vorticity and turbulence.


i would like to make  a simulation like this  https://www.youtube.com/
watch?v=8HWYUBcuFrA        when you zoom in there are  more particles and
more grid cells,  and where and when there is entropy, along the interface,
 more as well.  there seems to be a cooler water and a hot gas.. energy in
the gas at 14 secs seems to come from a chemical reaction or its a bug.
 This   sort of    Adaptive Multigrid reduce the problem to 1 dimension ,
in some ways and can give an tremendous boost.    And using a bottom with
alot of bump and reefs and shipwrecks.


Please forgive the long email... I have been researching CFD for 5 months
now, and  I'm drowning just to get a grip, and there are new developments
every week it seems.. narrow band flip.. etc..   crossover from astro
physics..    I have highlighted some areas in case you want to skim read
the email.



*-Are there or will there we any temperature gradients in this code or
would it be hard to add?   I am interested in heat because it gives so much
dynamics, weather and such , for free.  Internal breaking waves  can be
modeled.. *

   the 2d code here is old, but free, with no license restrictions, has
temperature gradients.
https://wissrech.ins.uni-bonn.de/research/projects/NaSt2D/index.html    I
havent worked much with it yet, i am overwhelmed trying to understand CFD
enough in itergrate existing code, with my balancing 2d creatures, that is
my research focus.


But the french code Gerris, Paris, Reef3d, has the restrictive license and
i have the 2d man who can surf, that i spend 5 years and 50,000 dollars to
develop. So i might want to sell a game someday, now my stuff is free.
But I don't want to show my biped walking source code because he is
 surfing or swimming ,  on my variant of their wave code, but i don't mind
showing my wave code mods if i need to make them.  Some is just artwork, I
really appreciate your choice of MIT license.  Or professional programmers
don't want to be involved, we need to eat.



* So now i want a wave and off shore winds create hollow barrels and jets
when they release gulped air , while other winds create sloppy waves. *


I would use a Keyframe kinematic  method to drive the waves, but moving the
interface, if that is possible,  or a mechanical pusher thing.
 To exercise creative control on the waves, it would suffice for me
to tweak parameters, wave height ,period , frequency, celerity, group
velocity,  and to adjust the ocean floor 2d profile.     implicit formula
for the boundary , if useful, I would try to compose the reef from that, or
use the height field approach.


I haven't fully studied all   the Weymouth or MIT code but
Maybe you can point me away or  toward some technologies.


I just found they released the code for this
http://pub.ist.ac.at/group_wojtan/projects/2015_Ando_ASFSfLS/index.html
 but I dont know if it can gulp bubbles of air.   When my airship sinks i
would  like bubbles to rise up ..

wrt
*The solver Speed.. Thanks for your explanation..  Now i see that grids do
not have to be square.*    adaptive multigrid seems to be the answer.


I do see that FFTs method scale the best on grids at 1024 x 1024  at
interactive rates, but I  am not sure how restrictive are   the
periodic boundaries,   or if one can solve pressure in a more approximate
way.  There are a few papers on this.


  The *Multigrid seems fast to converge and it could be the rendering
method  that is slow , after if   i am using too much grid  because of the
rendering technique which gives a fuzzy outline to the vortex rollups.  *



for speeding up , i am slight interested in  open CL and cudaify, or the
new .net Math library,
The math code in .net is now Vectorized for SIMD and matrix solving, i am
hoping to try that.

 and/or  use of shaders, but the code is not portable enough.   Also , i
can keep  GPU(s) busy with post processing or rendering  or maybe some
isolated grids


I think using Chimera grids, adaptive multi grid that can break up the grid
, or focus on the areas of entropy.  boundaries, or  vorticity..


I am also looking at
 Uof C Flash code,  level sets, VOFand chris  Batty variational cut cell
methods for sloshing, with a MAC grid, and the MAC code in tunabrains
tunabrain/incremental-fluids


From surfing , i can easily feel that , In overturning waves, vortices are
the dominant dynamic.


so i am wondering if i should give vorton methods are hard look
*http://gamma.cs.unc.edu/hybridfluid/golas-2012-hybridfluid.pdf
<http://gamma.cs.unc.edu/hybridfluid/golas-2012-hybridfluid.pdf>*



*Jacobian Free-Newton Krylov Discontinuous Galerkin Method and
Physics-Based Preconditioning *

*https://inldigitallibrary.inl.gov/sti/4096524.pdf
<https://inldigitallibrary.inl.gov/sti/4096524.pdf> * they are talking
about 50x improvements if one has prior knowledge of the boundaries, as I
understand.  I dont know how generally useful it might be.


the triangle mesh *ACLSVOF* technique is getting a lot of attention.


    I am in indonesia right now.    What is interesting in the sound in the
vortex, for the few time i manage to ride a surf board in there,. But now i
am injured and focused only on research and  simulation.  How wind
dramatically affect wave shape and power.   2d is fine because I could
never do justice to 3d now could a pc simulate it well enough.

There are alot  of counterintuitive realities in the vortex-dominated
impact zone and rip current area, realities that drown people or collide
them to the reef.  i learned that paddling with the fingers spread saves
energy and works as well as using fingers together, due to turbulence and
vortex action.  I have learned that there are two or three  pairs of
counter rotating vortices one must aim for  when looking into
the gaping maw of  a breaking wave 10 ft or so, that is jacking up on the
reef , with a 16 second period wave.   Choosing the right place to do the
duck dive,  to carefully time  submerging ones board and oneself   to
pierce the wave , so that the 12 foot of water is now over you and tilting
the board  can give some control, to use its shape and boyancy to get
propelled out  of the back of the wave, further out to sea,  and often
times, out of danger.



-thanks for any assistance... I have found a couple trivial  bugs, i'd be
glad to help with this code if you can guide me, and i find i can work with
it.

**Comment by damian-666** [comment]
I tried your latest test code.    so to get anything like water and air
seems to me the next thing to try is algebraic multigrid as preconditioner
- conjugate gradient.
  say if   it doesnt converge after 8 or if its two phase.   seems if i
  google the issue, all the papers say that.

besides what i sent earlier ,
i have a few papers seems like what you have .. but i dont understand it
well, was wondering if you thought it was worth a try.  I have java
versions somewhere too..  Let me know if i should find  those  but google
might  turn them up..
   should i try to make a wave tank if the two phase can work?

i see the papers try to achieve\* 1/800 density.*.. air in water, and seems
we can get snow flakes   in water and emergency bubbles.    all say to use
AMG +CG... or   using spectral methods with various tricks..

_http://www.hpcs.cs.tsukuba.ac.jp/~tatebe/research/paper/CM93-tatebe.pdf
http://www.hpcs.cs.tsukuba.ac.jp/~tatebe/research/paper/CM93-tatebe.pdf_

_http://ftp.demec.ufpr.br/CFD/bibliografia/MULTIGRID/Pereira_et_al_2006.pdf
http://ftp.demec.ufpr.br/CFD/bibliografia/MULTIGRID/Pereira_et_al_2006.pdf_

https://www.google.co.id/search?q=The+multigrid+preconditioned+conjugate+gradient+method.&rlz=1C1PQHB_enID617ID617&oq=The+multigrid+preconditioned+conjugate+gradient+method.&aqs=chrome..69i57j0l2.615j0j7&sourceid=chrome&ie=UTF-8

 I have some other code that does cut cell and conjugate gradient, which i
plan for my mutli-density hot dust and ash and volcanic, one phase stormy
sky.   But,   using just a  conjugate gradient solver, But, it does not
converge if i move the immersed paddle and the originators dont have the
desired to fix it.

 So... i might try to use lily pad for my air and water.      I want to
study it more and maybe help if i can.

They use AMG CG, and other solvers,  with or without level sets..... but
for my purpose to have  full NS solve from top to bottom is important to
that the bottom causes the wave to break.   Also for surfing , the
direction of the wave current  at surface,  as the wave breaks... is very
 important.. for lift..  the CIP method...
http://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/63952   seems
interesting to be to add detail to the surface..

Maybe later>>>>
And there are a lot of spectral IB methods.. they use FFT for the pressure
solve..  even in 2 phase

  FFT for the pressure solve is the first stam paper i saw I can get a
1024x1024 grid.  People say it wont work with IB,  But the papers claim (
even peskin, using some tricks, that immersed bodies massless or not ,  or
with a" twin"   can be placed in there , maybe if the IB object is small or
other conditions apply)   its just a gas pressure solve , for air does not
need to be exact.

There is mention of use of level sets, but if we can fix this,  i have some
relevant ideas.  like using level sets on the bubble that emergy if Level
of detail wants to show it.    But .. i would like an uneven bottom to
affect the breaking waves.. so using it for the surface would need to have
the grid affect the level set, not merely advect the surface level set.   I
have also studied som CIP code.. ,.... I was hoping to reduce to 1D the
surface but these go to 3d from 2d...

And i see vorton /flux / vof  methods.

if you have the turbulence in there, maybe best to remove it...for now...
im researching but there is too much to learn.  i end up at
 infinite dimensional LIE groups and Riemann surfaces.. einstein level
stuff...

thanks..

**Comment by damian-666** [comment]
Hello again Dr...

Lily Pad
re:  issue with two phase stability..

I'm back because my intuition tells me this code might be the best. I was
looking at the free surface module,  two phase and wondering if it is "code
complete"  or there is a todo list.    What I don't see is any surface
tension or tracking or special treatments as in CIP, VOF, or level set, cut
cell with "ghost cells" or if the BDIM can resolve the air water boundary
as it does the solid/ water   ..

 Could your code be used as a numerical wave tank with waves breaking due
to the bottom bathymetry ( in 2d) and gulping air  and affected by wind (
on shore is messy waves with less impact on breaking  , offshore wind fills
barrel shaped waves) .
1. My main question is is the code currently complete with bugs, or if code
   from somewhere else should be merged, or if i'm looking for too much..  I
   am just now reading your paper about conservative VOF.

I was looking at  wave code, numerical  wave tank ,  and i ran across this
mans work and he refers to Weymouth quite a bit.

https://github.com/melmi/aban2     i though you might want to  take a look
at it and see if it is something that was planned for lily pad.. i haven't
tried it because i  completely burned out at the moment, the code is linux
oriented, have downed a terabyte of stuff , and still lack direction.
But you might take a look at see if it is code might  fits..
1.  Also, if I had time , should i try the other solver?    putting  AMG as
   a preconditioner for a  conjugate gradient solver  in there.

An application of Cartesian-grid and volume-of-fluid methods to numerical
ship hydrodynamics
http://oai.dtic.mil/oai/oai?verb=getRecord&metadataPrefix=html&identifier=ADP023891

I have seen good demos  with coarse or adaptive,  cartesian grids and good
interpolation and interfacing techniques.

I have some FLIP code, and was going to try Nast2d.. but this Naval code i
trust.

But the new stuff keep pouring in endlessly and I need some direction.   I
am willing to help on Lily pad if there are things you suggest I should try
and if i find the time.

thanks.

**Comment by damian-666** [comment]
ok  sorry to bug you but,   i found the cVOF slosh tank, and  i was
wondering if the source is anywhere or if its already merged in lily pad.
(the cVOF has a very well defined interface though) but ..its oil and water
0.9 to 1.. and i was wondering if we could do 1 to 100 or 1 to 10...  the
bubbles  are nice...  also i see other papers and  i am interested in the
velocity on the surface, for surfing..  the images that show the circles
moving as depth increase, flattening, would be ideal.      if i can help ,
with guidance, i might be able to solve something.

 i see a recent paper on Galerkin or other interpolation  methods,
extrapolating a rough grid can give amazing sub-grid thin splash features
with cut cells.    only the interface is given more nodes based on
curvature, entropy, and the grid is fixed ..

found it here they work if i down load the Jar files...

http://web.mit.edu/weymouth/www/

TITLE: An Application of Cartesian-Grid and Volume-of-Fluid Methods to
Numerical Ship Hydrodynamics

wonder if these papers would help with the free interface or if it can be
treated like a boundary, but ..with more surface tension..

Detailed Water with Coarse Grids: Combining Surface Meshes and Adaptive
Discontinuous Galerkin

http://www.flow.kth.se/sites/flow.kth.se/files/TSZ-Book-ch-1-4.pdf

the CIP method..

or if this code is available ..
http://www.sciencedirect.com/science/article/pii/S0021999109006974
http://www.ingentaconnect.com/content/sname/jsr/2005/
00000049/00000002/art00002

An application of Cartesian-grid and volume-of-fluid methods to numerical
ship hydrodynamics
http://oai.dtic.mil/oai/oai?verb=getRecord&metadataPrefix=html&identifier=ADP023891

RANS Computational Fluid Dynamics Predictions of Pitch and Heave Ship
Motions in Head Seas

thanks..

**Comment by damian-666** [comment]
​hello.. i am back to this.. just a quick thing  on TWO PHASE  i went to
your earlier 1.0 code... and its better, but has different issues..   might
be a clue ..

i changed a parameter in _bold here_ below   i think dt and gamma....
havent tried sloshing yet... but its clearly better.

the other solver wasn't stable when i tried...would love to see a numerical
wave tank with a fairly steady  wind on it but if this isn't the whole
solution...or just part... i could use advice.

 i wasn't sure if you were moving towards JS and that stream..and
vortons...any ways..

seemst the surface tension seems inadequate to keep the air out..

curious about VOF code in java i couldnt find your source...

thanks..   too much code out there...i cant seem to  get progress on my
boats...

/**********************************
TwoPhase class

Extends BDIM by adding two-phase modeling

This means we need to track the free interface and apply the
variable density to the pressure gradient

example code:
**************************************_/
TwoPhase flow;
void setup(){
  int n=(int)pow(2,7)+2, m=(int)pow(2,6)+2;
  flow = new TwoPhase(n,m,_1,001*);
  flow.f.eq(0,m,n,0,m);
  flow.u = new VectorField(n,m,0,0);
}
void draw(){
  flow.update();
  flow.update2();
  flow.f.display();
}

void settings()
{
 size(400,200);
}
class TwoPhase extends BDIM{
  FreeInterface f,f0;

  TwoPhase( int n, int m, float dt, Body body, float nu, boolean QUICK,
float g, float gamma ){
    super( n, m, dt, body, nu, QUICK);
    f  = new FreeInterface( n, m, gamma );
    f0 = new FreeInterface( n, m, gamma );
    this.g.y = g;
  }
  TwoPhase( int n, int m, float dt, float g ){
    this( n, m, dt, new CircleBody(0,0,0.,new Window()), 1, false, g, 0.1);
  }

  void update(){
    f.strang = (f.strang+1)%2; // strang operator splitting
    getRhoCoeffs();
    f0.eq(f);
    f.advect( dt, u0 );
    super.update();
  }
  void update2(){
    getRhoCoeffs();
    f.eq(f0);
    f.advect( dt, u0, u );
    super.update2();
  }
  void getRhoCoeffs(){
    rhoi.eq(f.rho().inv());
    c.eq(del.times(rhoi.times(dt)));
  }
}
